version:  "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: bytedb
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
    ports:
        - 3333:3306
    networks:
        - springboot-mysql-net

  app:
    container_name: app
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 8080:8080
    depends_on:
        - mysqldb
    environment:
        MYSQL_HOST: mysqldb
        MYSQL_PORT: 3306
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
    networks:
        - springboot-mysql-net
    restart: on-failure

networks:
  springboot-mysql-net:
